version: "3"

networks:
  corp:
    driver: bridge

services:
  web:
    container_name: web
    networks:
      - corp
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"